using System.Text;
using System.Text.RegularExpressions;

namespace AssetPathGenerator;

public static class Program
{
    private const string Namespace = "Visualisation.Core.Display.Materials";
    private const string RootClassName = "MaterialTextured";
    private const string AssetRootFolder = "Textures";

    /// <summary>
    /// Defines the filename suffixes to identify PBR material maps.
    /// The script will look for files ending with these strings (case-insensitive).
    /// </summary>
    private static readonly Dictionary<string, string[]> MaterialMapIdentifiers = new()
    {
        { "albedo", ["_albedo", "albedo"] },
        { "normal", ["_normal", "normal"] },
        { "metallic", ["_metallic", "metallic"] },
        { "roughness", ["_roughness", "_height", "roughness", "height"] },
        { "ao", ["_ao", "ao"] }
    };

    public static void Main(string[] args)
    {
        if (args.Length is 0 or > 2)
        {
            Console.WriteLine("Please provide the path to the source asset folder.");
            Console.WriteLine("Usage: MaterialGenerator <source_directory> [output_file]");
            Console.WriteLine(
                @"Example: MaterialGenerator ""C:\MyGame\Assets\Textures"" ""./Generated/Material.Generated.cs""");
            Console.ResetColor();
            return;
        }

        var sourceAssetFolder = args[0];
        var outputFile = args.Length > 1 ? args[1] : "./Generated/Material.Generated.cs";

        Console.WriteLine("Starting Material Generation...");
        Console.WriteLine($"  Source: {Path.GetFullPath(sourceAssetFolder)}");
        Console.WriteLine($"  Output: {Path.GetFullPath(outputFile)}");

        var sourceDirectoryInfo = new DirectoryInfo(sourceAssetFolder);
        if (!sourceDirectoryInfo.Exists)
        {
            Console.ForegroundColor = ConsoleColor.Red;
            Console.WriteLine($"Error: Source directory not found at '{sourceDirectoryInfo.FullName}'");
            Console.ResetColor();
            return;
        }

        var outputFileInfo = new FileInfo(outputFile);
        outputFileInfo.Directory?.Create();

        var codeBuilder = new StringBuilder();

        codeBuilder.AppendLine("// <auto-generated>");
        codeBuilder.AppendLine("//     This code was generated by a tool. Any changes will be overwritten.");
        codeBuilder.AppendLine("// </auto-generated>");
        codeBuilder.AppendLine();
        codeBuilder.AppendLine($"namespace {Namespace};");
        codeBuilder.AppendLine();
        codeBuilder.AppendLine($"public sealed partial class {RootClassName}");
        codeBuilder.AppendLine("{");

        ProcessDirectory(sourceDirectoryInfo, codeBuilder, 1, sourceDirectoryInfo.FullName);

        codeBuilder.AppendLine("}");

        File.WriteAllText(outputFileInfo.FullName, codeBuilder.ToString());

        Console.ForegroundColor = ConsoleColor.Green;
        Console.WriteLine($"Successfully generated materials at: '{outputFileInfo.FullName}'");
        Console.ResetColor();
    }

    /// <summary>
    /// Recursively processes directories, generating material properties and nested static classes.
    /// </summary>
    private static void ProcessDirectory(
        DirectoryInfo directoryInfo,
        StringBuilder sb,
        int indentationLevel,
        string rootPath)
    {
        var indent = new string(' ', indentationLevel * 4);
        var subDirs = directoryInfo.GetDirectories();

        var materialDirs = new List<DirectoryInfo>();
        var categoryDirs = new List<DirectoryInfo>();

        foreach (var subDir in subDirs)
        {
            if (IsMaterialDirectory(subDir))
            {
                materialDirs.Add(subDir);
            }
            else
            {
                categoryDirs.Add(subDir);
            }
        }

        var categoryNames = new HashSet<string>(
            categoryDirs.Select(dir => ToPascalCaseIdentifier(dir.Name))
        );

        foreach (var materialDir in materialDirs)
        {
            var materialName = ToPascalCaseIdentifier(materialDir.Name);
            if (categoryNames.Contains(materialName))
            {
                materialName += "Material";
            }

            var materialMaps = GetMaterialPaths(materialDir, rootPath);

            sb.AppendLine($"{indent}public static Materials.MaterialTextured {materialName} {{ get; }} = new(");
            sb.AppendLine($"{indent}    \"{ToSentenceCase(materialName)}\",");
            sb.AppendLine($"{indent}    \"{materialMaps["albedo"]}\",");
            sb.AppendLine($"{indent}    \"{materialMaps["normal"]}\",");
            sb.AppendLine($"{indent}    \"{materialMaps["metallic"]}\",");
            sb.AppendLine($"{indent}    \"{materialMaps["roughness"]}\",");
            sb.AppendLine($"{indent}    \"{materialMaps["ao"]}\"");
            sb.AppendLine($"{indent});");
            sb.AppendLine();
        }

        foreach (var categoryDir in categoryDirs)
        {
            var tempContentBuilder = new StringBuilder();
            ProcessDirectory(categoryDir, tempContentBuilder, indentationLevel + 1, rootPath);

            if (tempContentBuilder.Length > 0)
            {
                var className = ToPascalCaseIdentifier(categoryDir.Name);
                sb.AppendLine($"{indent}public static partial class {className}");
                sb.AppendLine($"{indent}{{");
                sb.Append(tempContentBuilder);
                sb.AppendLine($"{indent}}}");
                sb.AppendLine();
            }
        }
    }

    /// <summary>
    /// Checks if a directory contains a full set of PBR textures.
    /// </summary>
    private static bool IsMaterialDirectory(DirectoryInfo directory)
    {
        var files = directory.GetFiles();
        foreach (var mapType in MaterialMapIdentifiers)
        {
            bool found = mapType.Value.Any(identifier =>
                files.Any(f => FileContainsIdentifier(f, identifier))
            );
            if (!found) return false;
        }

        return true;
    }

    /// <summary>
    /// Checks if a file contains the specified identifier in its name (excluding extension).
    /// </summary>
    /// <param name="file">The file to check</param>
    /// <param name="identifier">The identifier to look for in the filename</param>
    /// <returns>True if the file contains the identifier, false otherwise</returns>
    private static bool FileContainsIdentifier(FileInfo file, string identifier)
    {
        return !Path.GetFileName(file.Name).EndsWith(".meta") &&
            Path.GetFileNameWithoutExtension(file.Name).Contains(identifier, StringComparison.OrdinalIgnoreCase);
    }

    /// <summary>
    /// Gets the paths for a known material directory.
    /// </summary>
    private static Dictionary<string, string> GetMaterialPaths(DirectoryInfo directory, string rootPath)
    {
        var files = directory.GetFiles();
        var foundMaps = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);

        foreach (var mapType in MaterialMapIdentifiers)
        {
            FileInfo? foundFile = null;
            foreach (var identifier in mapType.Value)
            {
                foundFile = files.FirstOrDefault(f => FileContainsIdentifier(f, identifier));
                if (foundFile != null) break;
            }

            var relativePath = Path.GetRelativePath(rootPath, foundFile!.FullName).Replace('\\', '/');
            foundMaps[mapType.Key.ToLowerInvariant()] = $"{AssetRootFolder}/{relativePath}";
        }

        return foundMaps;
    }

    private static string ToPascalCaseIdentifier(string name)
    {
        string sanitized = Regex.Replace(name, @"[^a-zA-Z0-9_]", "_");
        var parts = sanitized.Split(['_'], StringSplitOptions.RemoveEmptyEntries);
        var pascalCasedBuilder = new StringBuilder();
        foreach (var part in parts)
        {
            if (string.IsNullOrEmpty(part)) continue;
            pascalCasedBuilder.Append(char.ToUpperInvariant(part[0]));
            pascalCasedBuilder.Append(part.Substring(1));
        }

        string finalIdentifier = pascalCasedBuilder.ToString();
        if (string.IsNullOrWhiteSpace(finalIdentifier)) return "_";
        if (char.IsDigit(finalIdentifier[0])) return "_" + finalIdentifier;
        return finalIdentifier;
    }

    private static string ToSentenceCase(string pascalCase)
    {
        return Regex.Replace(pascalCase, "[a-z][A-Z]", m => $"{m.Value[0]} {m.Value[1]}");
    }
}