using OpenTK.Windowing.GraphicsLibraryFramework;

using Visualisation.Core.Inputs;

namespace Visualization.UiLayer.Inputs;

internal static class KeyMap
{
    internal static readonly Dictionary<InputKey, Keys> OpenTkKeysMap = new()
    {
        { InputKey.F1, Keys.F1 },
        { InputKey.F2, Keys.F2 },
        { InputKey.F3, Keys.F3 },
        { InputKey.F4, Keys.F4 },
        { InputKey.F5, Keys.F5 },
        { InputKey.F6, Keys.F6 },
        { InputKey.F7, Keys.F7 },
        { InputKey.F8, Keys.F8 },
        { InputKey.F9, Keys.F9 },
        { InputKey.F10, Keys.F10 },
        { InputKey.F11, Keys.F11 },
        { InputKey.F12, Keys.F12 },
        { InputKey.F13, Keys.F13 },
        { InputKey.F14, Keys.F14 },
        { InputKey.F15, Keys.F15 },
        { InputKey.F16, Keys.F16 },
        { InputKey.F17, Keys.F17 },
        { InputKey.F18, Keys.F18 },
        { InputKey.F19, Keys.F19 },
        { InputKey.F20, Keys.F20 },
        { InputKey.F21, Keys.F21 },
        { InputKey.F22, Keys.F22 },
        { InputKey.F23, Keys.F23 },
        { InputKey.F24, Keys.F24 },
        { InputKey.KeyPad0, Keys.KeyPad0 },
        { InputKey.KeyPad1, Keys.KeyPad1 },
        { InputKey.KeyPad2, Keys.KeyPad2 },
        { InputKey.KeyPad3, Keys.KeyPad3 },
        { InputKey.KeyPad4, Keys.KeyPad4 },
        { InputKey.KeyPad5, Keys.KeyPad5 },
        { InputKey.KeyPad6, Keys.KeyPad6 },
        { InputKey.KeyPad7, Keys.KeyPad7 },
        { InputKey.KeyPad8, Keys.KeyPad8 },
        { InputKey.KeyPad9, Keys.KeyPad9 },
        { InputKey.KeyPadDecimal, Keys.KeyPadDecimal },
        { InputKey.KeyPadDivide, Keys.KeyPadDivide },
        { InputKey.KeyPadMultiply, Keys.KeyPadMultiply },
        { InputKey.KeyPadSubtract, Keys.KeyPadSubtract },
        { InputKey.KeyPadAdd, Keys.KeyPadAdd },
        { InputKey.KeyPadEnter, Keys.KeyPadEnter },
        { InputKey.KeyPadEqual, Keys.KeyPadEqual },
        { InputKey.Escape, Keys.Escape },
        { InputKey.D1, Keys.D1 },
        { InputKey.D2, Keys.D2 },
        { InputKey.D3, Keys.D3 },
        { InputKey.D4, Keys.D4 },
        { InputKey.D5, Keys.D5 },
        { InputKey.D6, Keys.D6 },
        { InputKey.D7, Keys.D7 },
        { InputKey.D8, Keys.D8 },
        { InputKey.D9, Keys.D9 },
        { InputKey.D0, Keys.D0 },
        { InputKey.A, Keys.A },
        { InputKey.B, Keys.B },
        { InputKey.C, Keys.C },
        { InputKey.D, Keys.D },
        { InputKey.E, Keys.E },
        { InputKey.F, Keys.F },
        { InputKey.G, Keys.G },
        { InputKey.H, Keys.H },
        { InputKey.I, Keys.I },
        { InputKey.J, Keys.J },
        { InputKey.K, Keys.K },
        { InputKey.L, Keys.L },
        { InputKey.M, Keys.M },
        { InputKey.N, Keys.N },
        { InputKey.O, Keys.O },
        { InputKey.P, Keys.P },
        { InputKey.Q, Keys.Q },
        { InputKey.R, Keys.R },
        { InputKey.S, Keys.S },
        { InputKey.T, Keys.T },
        { InputKey.U, Keys.U },
        { InputKey.V, Keys.V },
        { InputKey.W, Keys.W },
        { InputKey.X, Keys.X },
        { InputKey.Y, Keys.Y },
        { InputKey.Z, Keys.Z },
        { InputKey.Minus, Keys.Minus },
        { InputKey.Equal, Keys.Equal },
        { InputKey.Tab, Keys.Tab },
        { InputKey.LeftBracket, Keys.LeftBracket },
        { InputKey.RightBracket, Keys.RightBracket },
        { InputKey.CapsLock, Keys.CapsLock },
        { InputKey.Semicolon, Keys.Semicolon },
        { InputKey.Apostrophe, Keys.Apostrophe },
        { InputKey.LeftShift, Keys.LeftShift },
        { InputKey.Comma, Keys.Comma },
        { InputKey.Period, Keys.Period },
        { InputKey.Slash, Keys.Slash },
        { InputKey.LeftCtrl, Keys.LeftControl },
        { InputKey.LeftSuper, Keys.LeftSuper },
        { InputKey.LeftAlt, Keys.LeftAlt },
        { InputKey.Space, Keys.Space },
        { InputKey.RightAlt, Keys.RightAlt },
        { InputKey.RightSuper, Keys.RightSuper },
        { InputKey.Left, Keys.Left },
        { InputKey.Right, Keys.Right },
        { InputKey.Up, Keys.Up },
        { InputKey.Down, Keys.Down }
    };
}